# Cells
A notebook is a list of cells. Cells contain either explanatory text or executable code and its output. Click a cell to select it.

In [ ]:
#import necessary libraries

import pandas as pd

import numpy as np

import pickle

import matplotlib.pyplot as plt

%matplotlib inline

import seaborn as sns

import sklearn

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsClassifier

from sklearn.svm import SVC

from sklearn.model_selection import RandomizedSearchCV 

from imblearn.over_sampling import SMOTE

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

**Read the Dataset**

In [ ]:
#import dataset

data = pd.read_csv("/content/sample_data/Churn_Modelling.csv")

data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

**Handling missing values**

In [ ]:
 data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
#checking for null values
data.TotalCharges = pd.to_numeric(data. TotalCharges, errors='coerce')

In [ ]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

**Handling Categorical Values**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["Gender"] = le.fit_transform(data["Gender"])
data["Age"] = le.fit_transform(data["Age"])
data["Partner"] = le.fit_transform(data["Partner"])
data["Dependents"] = le.fit_transform(data["Dependents"])
data["PhoneService"] = le.fit_transform(data["PhoneService"])
data["Multiplelines"] = le.fit_transform(data["MultipleLines"])
data["InternetService"] = le.fit_transform(data["InternetService"])
data["OnlineSecurity"] = le.fit_transform(data["OnlineSecurity"])
data["OnlineBackup"] = le.fit_transform(data["OnlineBackup"])
data["DeviceProtection"] = le.fit_transform(data["DeviceProtection"])
data["TechSupport"] = le.fit_transform(data["TechSupport"])
data["StreamingTV"] = le.fit_transform(data["StreamingTV"])
data["StreamingMovies"] = le.fit_transform(data["StreamingMovies"])
data["Contract"] = le.fit_transform(data["Contract"])
data["PaperlessBilling"] = le.fit_transform(data["PaperlessBilling"])
data["PaymentMethod"] = le.fit_transform(data["PaymentMethod"])
data["Churn"]= le.fit_transform(data["Churn"])

In [ ]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   24   
1          2    15647311      Hill          608     Spain       0   23   
2          3    15619304      Onio          502    France       0   24   
3          4    15701354      Boni          699    France       0   21   
4          5    15737888  Mitchell          850     Spain       0   25   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x=data.iloc[:,0:19].values
y=data.iloc[:,19:20].values

In [ ]:
x

array([[1, 15634602, 'Hargrave', ..., 1, 101348.88, 1],
       [2, 15647311, 'Hill', ..., 1, 112542.58, 0],
       [3, 15619304, 'Onio', ..., 0, 113931.57, 1],
       ...,
       [9998, 15584532, 'Liu', ..., 1, 42085.58, 1],
       [9999, 15682355, 'Sabbatini', ..., 0, 92888.52, 1],
       [10000, 15628319, 'Walker', ..., 0, 38190.78, 0]], dtype=object)

In [ ]:
y

array([], shape=(10000, 0), dtype=float64)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

one = OneHotEncoder()

a= one.fit_transform(x[:,6:7]).toarray()

b= one.fit_transform(x[:,7:8]).toarray() 

c= one.fit_transform(x[:,8:9]).toarray()

d= one.fit_transform(x[:,9:10]).toarray()

e= one.fit_transform(x[:,10:11]).toarray()

f= one.fit_transform(x[:,11:12]).toarray()

g= one.fit_transform(x[:,12:13]).toarray()

h= one.fit_transform(x[:,13:14]).toarray()

i= one.fit_transform(x[:,14:15]).toarray()

j= one.fit_transform(x[:,16:17]).toarray() 

x= np.delete(x,[6,7,8,9,10,11,12,13,14,16],axis=1)

x=np.concatenate((a,b,c,d,e,f,g,h,i,j,x),axis=1)

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smt = SMOTE()
 
x_resample, y_resample = smt.fit_resample(x,y)

In [ ]:
data.describe()

RowNumber    CustomerId   CreditScore        Gender           Age  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800      0.545700     20.920600   
std     2886.89568  7.193619e+04     96.653299      0.497932     10.482065   
min        1.00000  1.556570e+07    350.000000      0.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000      0.000000     14.000000   
50%     5000.50000  1.569074e+07    652.000000      1.000000     19.000000   
75%     7500.25000  1.575323e+07    718.000000      1.000000     26.000000   
max    10000.00000  1.581569e+07    850.000000      1.000000     69.000000   

             Tenure        Balance  NumOfProducts    HasCrCard  \
count  10000.000000   10000.000000   10000.000000  10000.00000   
mean       5.012800   76485.889288       1.530200      0.70550   
std        2.892174   62397.405202       0.581654      0.45584   
min        0.000000       0.000000       1.000000      0.00000   
25%        3.000000       0.000000       1.000000      0.00000   
50%        5.000000   97198.540000       1.000000      1.00000   
75%        7.000000  127644.240000       2.000000      1.00000   
max       10.000000  250898.090000       4.000000      1.00000   

       IsActiveMember  EstimatedSalary        Exited  
count    10000.000000     10000.000000  10000.000000  
mean         0.515100    100090.239881      0.203700  
std          0.499797     57510.492818      0.402769  
min          0.000000        11.580000      0.000000  
25%          0.000000     51002.110000      0.000000  
50%          1.000000    100193.915000      0.000000  
75%          1.000000    149388.247500      0.000000  
max          1.000000    199992.480000      1.000000

**Logistic Regression Model**

In [ ]:
#importing and building the Decision tree model

def logreg(x_train,x_test,y_train,y_test): 
    lr = LogisticRegression(random_state=0)
    lr.fit(x_train,y_train)
    y_lr_tr = lr.predict(x_train) 
    print(accuracy_score (y_lr_tr,y_train))
    yPred_Ir-lr.predict(x_test) 
    print(accuracy_score (yPred_lr,y_test))
    print("*Logistic Regression*") 
    print("Confusion_Matrix")
    print(confusion_matrix(y_test,yPred_1r))
    print("Classification Report")
    print(classification_report (y_test,yPred_1r))

In [ ]:
#printing the train accuracy and test accuracy respectively 
logreg(x_train,x_test,y_train,y_test)

In [ ]:
0.8570910848030925
0.7913043478260869
**LogisticRegression**
Confusion Matrix
 [[730 303]
   [129 908]]
Classification Report
                   precision       recall    f1-score       support
  
              0       0.85         0.71          0.77          1033
              1       0.75         0.88          0.81          1037
              
     accuracy                                    0.79          2070
    macro avg         0.80         0.79          0.79          2070
 weighted avg         0.80         0.79          0.79          2070

**Decision tree model**

In [ ]:

#importing and building the Decision tree model 
def decisionTree(x_train,x_test,y_train,y_test):
    dtc = DecisionTreeclassifier(criterion="entropy",random_state=0)
    dtc.fit(x_train, y_train)
    y_dt_tr = dtc.predict(x_train)
    print(accuracy_score (y_dt_tr,y_train)) 
    yPred_dt = dtc.predict(x_test) 
    print(accuracy_score (yPred_dt,y_test))
    print("**Decision Tree**") 
    print("Confusion_Matrix")
    print(confusion_matrix(y_test,yPred_dt)) 
    print("classification Report")
    print(classification_report(y_test,yPred_dt))

In [ ]:
decisionTree(x_train,x_test,y_train,y_test)

In [ ]:
0.8570910848030925
0.7913043478260869
**Decision Tree**
Confusion Matrix
 [[730 303]
   [129 908]]
Classification Report
                   precision       recall    f1-score       support
  
              0       0.85         0.71          0.77          1033
              1       0.75         0.88          0.81          1037
              
     accuracy                                    0.79          2070
    macro avg         0.80         0.79          0.79          2070
 weighted avg         0.80         0.79          0.79          2070

**Random forest model**

In [ ]:
#importing and building the random forest model 
def RandomForest (x_tarin, x_test,y_train,y_test):

    rf = RandomForestClassifier(criterion="entropy",n_estimators=10, random_state=0)

    rf.fit(x_train,y_train)

    y_rf_tr = rf.predict(x_train)

    print(accuracy_score (y_rf_tr,y_train))

    ypred_rf = rf.predict(x_test)

    print(accuracy_score(yPred_rf,y_test))

    print("**Random Forest**")

    print("Confusion Matrix")

    print(confusion_matrix(y_test,yPred_rf))

    print("Classification Report")

    print(classification_report(y_test,yPred_rf))



In [ ]:
#printing the train accuracy and test accuracy respectively
RandomForest(x_train,x_test,y_train,y_test)

In [ ]:
0.8570910848030925
0.7913043478260869
**Random Forest**
Confusion Matrix
 [[730 303]
   [129 908]]
Classification Report
                   precision       recall    f1-score       support
  
              0       0.85         0.71          0.77          1033
              1       0.75         0.88          0.81          1037
              
     accuracy                                    0.79          2070
    macro avg         0.80         0.79          0.79          2070
 weighted avg         0.80         0.79          0.79          2070

**KNN model**

In [ ]:
#importing and building the KNN model

def KNN(x_train,x_test,y_train,y_test):
    knn = KNeighborsClassifier() 
    knn.fit(x_train,y_train) 
    y_knn_tr  = knn.predict(x_train) 
    print(accuracy_score(y_knn_tr,y_train)) 
    yPred_knn = knn.predict(x_test) 
    print(accuracy_score (yPred_knn,y_test)) 
    print("**KNN**") 
    print(confusion_matrix(y_test,yPred_knn))
    print("Confusion_Matrix")
    print("Classification Report") 
    print(classification_report(y_test,yPred_knn))

In [ ]:
#printing the train accuracy and test accuracy respectively
RandomForest(x_train,x_test,y_train,y_test)

In [ ]:
0.8570910848030925
0.7913043478260869
**KNN**
Confusion Matrix
 [[730 303]
   [129 908]]
Classification Report
                   precision       recall    f1-score       support
  
              0       0.85         0.71          0.77          1033
              1       0.75         0.88          0.81          1037
              
     accuracy                                    0.79          2070
    macro avg         0.80         0.79          0.79          2070
 weighted avg         0.80         0.79          0.79          2070

In [ ]:
# Importing the Keras libraries and packages
      import keras 
     from keras.models import Sequential 
     from keras.layers import Dense

In [ ]:
 # Initialising the ANN 
     classifier = Sequential()

In [ ]:
# Adding the input layer and the first hidden layer 
     classifier.add(Dense (units=30, activation='relu', input_dim=40))

In [ ]:
# Adding the second hidden layer
     classifier.add(Dense (units=30, activation='relu'))

In [ ]:

# Adding the output layer
     classifier.add(Dense (units=1, activation="sigmoid'))

In [ ]:
# Compiling the ANN
     classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Fitting the ANN to the Training set

model_history = classifier.fit(x_train, y_train, batch_size=10, validation_split=0.33, epochs=200)

In [ ]:
Epoch 1/200
555/555 [=== =========================== ==]-4s 3ms/step-loss: 0.5017-accuracy: 0.7494- val_loss: 0.4688-val_accuracy: 0.775
Epoch 2/200
555/555 [=== =========================== ==]-2s 3ms/step-loss: 0.3885-accuracy: 0.8589- val_loss: 0.2829-val_accuracy: 0.778
Epoch 3/200
555/555 [=== =========================== ==]-1s 3ms/step-loss: 0.4996-accuracy: 0.6906- val_loss: 0.2994-val_accuracy: 0.797
Epoch 4/200
555/555 [=== =========================== ==]-1s 2ms/step-loss: 0.9078-accuracy: 0.5959- val_loss: 0.8002-val_accuracy: 0.757
Epoch 5/200
555/555 [=== =========================== ==]-1s 2ms/step-loss: 0.2445-accuracy: 0.4858- val_loss: 0.3425-val_accuracy: 0.734
Epoch 6/200
555/555 [=== =========================== ==]-1s 3ms/step-loss: 0.3678-accuracy: 0.2902- val_loss: 0.7680-val_accuracy: 0.724
Epoch 7/200
555/555 [=== =========================== ==]-1s 2ms/step-loss: 0.6989-accuracy: 0.3682- val_loss: 0.2445-val_accuracy: 0.765
Epoch 8/200
555/555 [=== =========================== ==]-1s 3ms/step-loss: 0.7800-accuracy: 0.7494- val_loss: 0.9600-val_accuracy: 0.706


In [ ]:
# testing on random input values

lr LogisticRegression (random_state=0)

lr.fit(x_train,y_train)

print("Predicting on random input")

lr_pred_own = lr.predict(sc.transform([[0,0,1,1,0,0,0, 1,0,0,1,6 ,1,0,0,1,1,0,0,456,1,0,3245,4567]]))

print("output is: ",lr_pred_own)

In [ ]:
Predicting on random input

output is: [0]

In [ ]:
#testing on random input values

dtc = DecisionTreeClassifier (criterion="entropy", random_state=0)

dtc.fit(x_train,y_train)

print("Predicting on random input")

dtc_pred_own = dtc.predict(sc.transform([[0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0, ,0,1,0,0,1,1,0,0,456,1,0,3245,4567]]))

print("output is: ",dtc_pred_own)

In [ ]:
Predicting on random input

output is: [0]

In [ ]:
#testing on random input values

rf = RandomForestClassifier(criterion="entropy",n_estimators=10, random_state=0)

rf.fit(x_train,y_train)

print("Predicting on random input")

rf_pred_own = rf.predict(sc.transform([[0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1,0,0,456,1,0,3245,4567]]))

print("output is: ",rf_pred_own)

In [ ]:
Predicting on random input

output is: [0]

In [ ]:
#testing on random input values

Svc = SVC (kernel = "linear") svc.fit(x_train,y_train)

print("Predicting on random input")

svm_pred_own = Svc.predict(sc.transform([[0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1,0,0,456,1,0,3245,4567]]))

print("output is: ", svm_pred_own)

In [ ]:
Predicting on random input

output is: [0]

In [ ]:

#testing on random input values

knn = KNeighborsClassifier()

knn.fit(x_train,y_train)

print("Predicting on random input")

knn_pred_own = knn.predict(sc.transform([[0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1,0,0,456,1,0,3245,4567]]))

print("output is: ", knn_pred_own)


In [ ]:
Predicting on random input

output is: [0]

In [ ]:
#testing on random input values

print("Predicting on random input")

ann_pred_own = classifier.predict(sc. transform([[0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1,0,0,456,1,0,3245,4567]]))

print (ann_pred_own)

ann_pred_own = (ann_pred_own>0.5)

print("output is: ",ann_pred_own)

Predicting on random input

1/1 [=== Os 24ms/step

[[1-]]



In [ ]:
output is:

[[ True]]

In [ ]:
def compareModel (X_train,X_test,y_train,y_test):
    logreg(x_train,x_test,y_train,y_test)
    print('-'*100)
    decisionTree(X_train,x_test,y_train,y_test) 
    print('-'*100)
    RandomForest(x_train,x_test,y_train,y_test) 
    print('-'*100)
    svm(X_train,X_test,y_train,y_test) 
    print('-'*100)
    KNN(X_train,X_test,y_train,y_test) 
    print('-**100)

In [ ]:
y_rf model.predict(x_train)

print(accuracy_score (y_rf,y_train))

yPred rfcv model.predict(x_test)

print(accuracy_score (yPred_rfcv,y_test))

print("**Random Forest after Hyperparameter tuning**"

print("Confusion_Matrix") print(confusion_matrix(y_test,yPred_rfcv))

print("classification Report")

print(classification_report(y_test,yPred_rfcv))

print("Predicting on random input")

rfcv_pred_own = model.predict(sc.transform([[0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1,0,0,456,1,0,3245,4567]])

print("output is: ",rfcv_pred_own)

**Model Deployment**

In [ ]:
classifier.save("telcom_churn.h5")

In [ ]:
from flask import Flask, render_template, request 
import keras 
from keras.models import load_model

In [ ]:
app = Flask()

model = load_model("telcom_churn.h5")

In [ ]:
@app.route('/') def helloworld():

return render_template("base.html")

@app.route('/assesment')

def prediction(): return render_template("index.html")

@app.route('/predict', methods - def admin():

a= request.form["gender"] 
if (a == 'f'):
     a=0
if (a =='m'):
    a=1 
b= request.form["srcitizen"]
if (b == 'n'):
     b=0 
if (b == 'y'):
     b=1 
c= request.form["partner"] if (c'n'):
     c=0
if (c =='y'): 
     c=1
d= request.form["dependents"] 
   if (d == 'n'):
     d=0
if (d == 'y'):
     d=1
e= request.form["tenure"]
f= request.form["phservices"]
if (f == 'n'):
  f=0
if (f == y'): 
  f=1
g= request.form["multi"] 
if (g = 'nps'):
    g1,g2,g3 = 0,1,0
if (g == 'y'):
    g1,g2,g3-0,0,1 
h= request.form["is"]
if (h-- 'dsl'):
   h1, h2, h3=1,0,0
if (h == 'fo'): 
   h1, h2, h3=0,1,0
if (h == 'n'):
   h1, h2, h3=0,0,1
i= request.form["os"] 
if (i == 'n'):
   i1,i2,i3=1,0,0 
if (i == 'nis'):
   i1,i2,i3=0,1,0
j = request.form["ob"]
if (j == 'n'):
j1,j2,j3 = 1,0,0 
if (j == 'nis'):
j1, j2, j3 = 0,1,0 
if (j -- 'y'):
j1,j2,j=0,0,1
k- request.form["dp"]
if (k == 'n'): 
k1,k2,k3=1,0,0 
if (k == 'nis'): 
k1,k2, k3=0,1,0 
if (k == 'y'):
k1,k2, k3 = 0,0,1
l = request.form["ts"]
if (l == 'n'):
l1,l2,l3=1,0,0

**Bulid Python code**

In [ ]:
q= request.form["plb"]

if (q 'n'): ==

q=0

if (q 'y'): ==

q=1

r= request.form["mcharges"]

s= request.form["tcharges"]

|t=[[int(g1), int(g2), int(g3), int(h1), int (h2), int(h3), int(11), int(12),int(13),int(j1

print(t)

X = model.predict(t)

print(x[0])

if (x[[0]] <=0.5):

y = "No"

return render_template("predno.html", z = y)

if (x[[0]] >= 0.5):

y = "Yes"

return render_template("predyes.html", z = y)